import Head from "next/head";
import { Fragment } from "react";
import BudgetSvg from '../svg/Statistics.svg'


export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Budget App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container base-color  text-dark ">
        <div className="row">
          <div className="col-md-6">
             <BudgetSvg/>
          </div>

          <div className="col-md-6 mt-5 ">
            <h1>Track your expenses with Name.io</h1>
            <p>The new way of tracking your expenses. Create a family, add your family members and watch your incomes and expenses!</p>
          </div>
        </div>
      </main>
    </Fragment>
  );
}
