import Head from "next/head";
import { Fragment } from "react";
import BudgetSvg from '../svg/Statistics.svg'
import { useSession, getSession } from "next-auth/react";


export default function Home() {
  const { data: session } = useSession();
  return (
    <Fragment>
      <Head>
        <title>Budget App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container base-color mt-5 text-dark ">
        <div className="row">
          <div className="row text-center d-block d-sm-none">
            <h1>Budget App</h1>
          </div>
          <div className="col-md-6">
             <BudgetSvg/>
          </div>

          <div className="col-md-6 mt-5 ">
            <h2>Track your expenses with Name.io</h2>
            <p>The new way of tracking your expenses. Create a family, add your family members and watch your incomes and expenses!</p>
          </div>
        </div>
      </main>
    </Fragment>
  );
}
